-- 0020_seed_midwaypca_pois.sql
-- Migrates the 53 POIs that were previously stored in map-data/facilities/midwaypca/pois.geojson
-- into the pois table. Idempotent: skips rows whose label already exists.
-- building_id resolved by name; rows whose building name isn't in the DB get building_id = NULL.

insert into public.pois (label, poi_type, icon, level, geometry_geojson, notes, building_id)
select v.label, v.poi_type, v.icon, v.level, v.geometry_geojson, v.notes, v.building_id
from (values
  ('AC16A', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6882541, 33.9441536]}'::jsonb, 'Sanctuary control (basement). In big white fencing outside the emergency-exit stairwell behind the 2009 pulpit.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC16B', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6883057, 33.9439678]}'::jsonb, 'Sanctuary control (basement). In big white fencing outside the emergency-exit stairwell behind the 2009 pulpit.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('HP9', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6878915, 33.9440395]}'::jsonb, 'Narthex / front-lobby control. Basement: nursery playground, unit closest to the nursery entry.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('HP11', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6878826, 33.9440941]}'::jsonb, 'Narthex / front-lobby control. Basement: nursery playground, unit closest to the nursery entry.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('HP5', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6878901, 33.9440794]}'::jsonb, 'Children''s ministry room & hallway control. Basement: nursery playground, unit closest to the main-level lobby entry.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC5', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6879118, 33.9440319]}'::jsonb, 'Children''s ministry room & hallway control. Basement: mechanical room, end of hall near the concession-style kitchen.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC1', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6882276, 33.9439872]}'::jsonb, 'Special-needs nursery 1 control. Main level: catwalk behind the 2009 sanctuary pulpit.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC2', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6881548, 33.9441064]}'::jsonb, 'Infant nursery 2 control. Main level: catwalk behind the 2009 sanctuary pulpit.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC3', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6880776, 33.94409]}'::jsonb, 'Children nursery 3 control. Main level: catwalk behind the 2009 sanctuary pulpit.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC4', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6880617, 33.9440055]}'::jsonb, 'Youth ministry room 4 control. Main level: catwalk behind the 2009 sanctuary pulpit.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC15', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6880304, 33.9438957]}'::jsonb, 'Long hallway connecting church with school. Main level: in ceiling in front of the men''s restroom by the 2009 sanctuary.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('HP15', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6880485, 33.9438284]}'::jsonb, 'Long hallway connecting church with school. Main level: outside the southern lobby entrance toward the nursery entrance.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('HP12', 'hvac', 'hvac', 2, '{"type": "Point", "coordinates": [-84.6878932, 33.9438982]}'::jsonb, 'Choir practice room & music-ministry offices control. Upper level: roof access off the stairwell by the elevator.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('HP13', 'hvac', 'hvac', 2, '{"type": "Point", "coordinates": [-84.6878769, 33.9439634]}'::jsonb, 'Choir practice room & music-ministry offices control. Upper level: roof access off the stairwell by the elevator.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC12', 'hvac', 'hvac', 2, '{"type": "Point", "coordinates": [-84.6878791, 33.9439034]}'::jsonb, 'Choir practice room & music-ministry offices. Upper level: above the men''s robing room (ladder entry).', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC13', 'hvac', 'hvac', 2, '{"type": "Point", "coordinates": [-84.687865, 33.9439771]}'::jsonb, 'Choir practice room & music-ministry offices. Upper level: above the men''s robing room (ladder entry).', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC9', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6878734, 33.9440415]}'::jsonb, 'Narthex / front-lobby control. Upper level: above the women''s robing room in the choir practice room (ladder entry).', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AC11', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6878641, 33.9440972]}'::jsonb, 'Narthex / front-lobby control. Upper level: above the women''s robing room in the choir practice room (ladder entry).', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AH16A', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6881958, 33.9441153]}'::jsonb, 'Sanctuary air handler. Upper level: behind mechanical-room doors on the balcony, either side of the 2009 pulpit.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('AH16B', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6882431, 33.9439631]}'::jsonb, 'Sanctuary air handler. Upper level: behind mechanical-room doors on the balcony, either side of the 2009 pulpit.', (SELECT id FROM public.buildings WHERE name = '2009 Building (Church)' LIMIT 1)),
  ('HP7', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6878937, 33.9435633]}'::jsonb, 'Fellowship-hall classrooms. Main level: outside, next to the head pastor''s office.', (SELECT id FROM public.buildings WHERE name = 'Fellowship Hall' LIMIT 1)),
  ('HP8', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6878809, 33.9435669]}'::jsonb, 'Fellowship-hall classrooms. Main level: outside, next to the head pastor''s office.', (SELECT id FROM public.buildings WHERE name = 'Fellowship Hall' LIMIT 1)),
  ('HP10', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6878541, 33.9435582]}'::jsonb, 'Back-hallway access to Explorers/Harvesters/Light classrooms. Main level: outside, next to the head pastor''s office.', (SELECT id FROM public.buildings WHERE name = 'Fellowship Hall' LIMIT 1)),
  ('HP14A', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.687771, 33.9437262]}'::jsonb, 'Pastors'' offices — Marc''s office. Main level: outside, next to the head pastor''s office.', (SELECT id FROM public.buildings WHERE name = 'Fellowship Hall' LIMIT 1)),
  ('HP14B', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.687828, 33.9435879]}'::jsonb, 'Pastors'' offices — David''s office. Main level: outside, next to the head pastor''s office.', (SELECT id FROM public.buildings WHERE name = 'Fellowship Hall' LIMIT 1)),
  ('AC7', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6877517, 33.9435967]}'::jsonb, 'Fellowship-hall classrooms. Main level: in ceiling, long drop tiles in the pastor-offices hallway.', (SELECT id FROM public.buildings WHERE name = 'Fellowship Hall' LIMIT 1)),
  ('AC8', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6877199, 33.9437135]}'::jsonb, 'Fellowship-hall classrooms. Main level: in ceiling, long drop tiles in the pastor-offices hallway.', (SELECT id FROM public.buildings WHERE name = 'Fellowship Hall' LIMIT 1)),
  ('AC10', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6877609, 33.9435584]}'::jsonb, 'Explorers/Harvesters/Light classrooms. Main level: Light classroom storage closet, back-left corner.', (SELECT id FROM public.buildings WHERE name = 'Fellowship Hall' LIMIT 1)),
  ('AC6', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6876653, 33.943652]}'::jsonb, 'Fellowship-hall center. Roof unit: on the roof over the cafeteria kitchen.', (SELECT id FROM public.buildings WHERE name = 'Fellowship Hall' LIMIT 1)),
  ('BG', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6873978, 33.9434364]}'::jsonb, 'Kitchen, cafeteria, Latin room, computer lab, library, (main) music room, intern office, Sheri Purdue''s office. Outside, behind the kitchen and dumpster.', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('AC17', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6873834, 33.9435995]}'::jsonb, 'Beverage station / pantry hallway. Roof unit: on the roof over the cafeteria kitchen.', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('BG2', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6872725, 33.9438702]}'::jsonb, '1987 sanctuary. Fenced-in elementary playground; air handler in the boiler room.', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('BGF4', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6872198, 33.9436338]}'::jsonb, 'Matt Ross office (main level). Unit in the elementary-playground corner behind some bushes; AC in the Matt Ross office.', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('BGF1', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6873743, 33.9434326]}'::jsonb, 'Lower-level music room. Outside, behind the kitchen and dumpster (smaller than BG).', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('BGF2', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6873507, 33.9434259]}'::jsonb, 'Lower-level classrooms, kindergarten–3rd grade. Outside, behind the kitchen and dumpster.', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('BGF3', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6873298, 33.9434226]}'::jsonb, 'Lower-level classrooms, kindergarten–3rd grade. Outside, behind the kitchen and dumpster.', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('BGF5', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6871195, 33.9437335]}'::jsonb, 'Stairway & teachers''-lounge rooms (lower level). Fenced-in elementary playground.', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('BGF6', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.687112, 33.9439259]}'::jsonb, 'Lower-level classrooms: kindergarten, 4th & 5th grade. North side, just past the elementary playground; AC in ceiling of the school hallway (sticker-labeled tiles).', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('BGF7', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6871112, 33.943966]}'::jsonb, 'Lower-level classrooms: kindergarten, 4th & 5th grade. North side, just past the elementary playground; AC in ceiling of the school hallway (sticker-labeled tiles).', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('BGF8', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6870847, 33.9439787]}'::jsonb, 'Lower-level classrooms: kindergarten, 4th & 5th grade. North side, just past the elementary playground; AC in ceiling of the school hallway (sticker-labeled tiles).', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('Boiler', 'hvac', 'hvac', -1, '{"type": "Point", "coordinates": [-84.6872367, 33.9436839]}'::jsonb, 'Boiler. In the boiler room (serves the BG2 air handler).', (SELECT id FROM public.buildings WHERE name = '1987 Building (School)' LIMIT 1)),
  ('HPG1', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6889585, 33.9439137]}'::jsonb, 'Middle-school gym, locker rooms, concession stand. Outside, farthest side of the building from the church.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('HPG2', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6889704, 33.9438904]}'::jsonb, 'Middle-school gym, locker rooms, concession stand. Outside, farthest side of the building from the church.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('HPG3', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6889703, 33.9438648]}'::jsonb, 'Middle-school gym, locker rooms, concession stand. Outside, farthest side of the building from the church.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('HPG4', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6885798, 33.943867]}'::jsonb, 'Gym / locker rooms / concession. Outside, corner closest to the church nursery.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('ACG1', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6888982, 33.9438815]}'::jsonb, 'Locker room 1. In ceiling.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('ACG2', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6889222, 33.9437669]}'::jsonb, 'Locker room 2. In ceiling.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('ACG4', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6886269, 33.9438648]}'::jsonb, 'Above the concession room. In ceiling.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('MHPG1', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6889553, 33.9435455]}'::jsonb, 'All classrooms except the far end of the building. Outside, side closest to the pavilion and field.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('MHPG2', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6889124, 33.9435383]}'::jsonb, 'All classrooms except the far end of the building. Outside, side closest to the pavilion and field.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('MHPG3', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6888792, 33.9435356]}'::jsonb, 'All classrooms except the far end of the building. Outside, side closest to the pavilion and field.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('WU1', 'hvac', 'hvac', 1, '{"type": "Point", "coordinates": [-84.6885599, 33.9437792]}'::jsonb, 'Colloquium classroom. Wall unit attached to the wall closest to the church.', (SELECT id FROM public.buildings WHERE name = 'Gym / Middle School' LIMIT 1)),
  ('Main Water Shutoff', 'shutoff', 'shutoff', -1, '{"type": "Point", "coordinates": [-84.6882169, 33.9441392]}'::jsonb, 'Example non-HVAC POI — main water shutoff. Reposition in geojson.io.', NULL)
) as v(label, poi_type, icon, level, geometry_geojson, notes, building_id)
where not exists (
  select 1 from public.pois p where p.label = v.label
);
